### ISSUE TITLE
LED issue fixed? And feature proposal

### ISSUE THREAD

**Issue by MacSass** [EdenRidgway/XY-Wifi-Clock#1]
Hi @EdenRidgway : Where you able to figure out the LED issue with the dots highlighting unwanted elements? I referenced your project on the first thread of my orginal post now.

One more thing: I think it would be nice to integrate an automatic brightness change. Maybe 2 of your current alarm config slots could be used for this?

I´ll be watching this project, although Tasmota works pretty ok on the board for me too.

**Comment by EdenRidgway** [comment]
Hi @MacSass. Unfortunately I still haven't fixed that issue. Thanks for referencing the project on the thread.

Would the brightness change be instead of an alarm sound? For example dimming the display at night and having it go brighter in the morning? Or are you thinking of just a general brightness level setting?

**Comment by MacSass** [comment]
Hi, in deed I was just looking at changing brightness depending on time of day.
I´m not using it as alarm clock (especially as the 303WifiLC01 does not have a buzzer). I just use it as night clock and the display is to bright at night if not set to minimum level.

**Comment by EdenRidgway** [comment]
I have added a night and day brightness setting now. The dots issue has also been resolved.

**Comment by MacSass** [comment]
Uh - very nice ... I´ll check that out tomorrow.

Thanks!

**Comment by darkpoet78** [comment]
The new timezone implementation looks nice!  I've just flashed the new firmware.  It looks great.  I'm still very new to Arduino and coding... and I'd love to fool around more with this but flashing this device is a pain in the butt.  Is there any way to implement Arduino OTA?
